project:
  type: website
  
website:
  title: "Property Tax Explainer"
  navbar:
    left:
      - href: QuartoDoc.qmd
        text: Home
      - FAQ.qmd
      - About.qmd
    logo: "CCAOlogo.jpeg"
format:
  html:
    theme: zephyr
    css: custom.css
    toc: True
      