project:
  type: website
  
website:
  title: "Property Tax Explainer"
  navbar:
    left:
      - href: QuartoDoc.qmd
        text: Suburb
      - href: Example2.qmd
        text: North Chicago
      - href: Example3.qmd
        text: South Chicago
    logo: "CCAOlogo.jpeg"
    
format:
  html:
    theme: zephyr
    css: custom.css
    toc: true
