# About the Cook County Assessor's Office

## Cook County Assessor's Office Mission and Values
### OUR MISSION
The mission of the Cook County Assessor’s Office is to deliver accurate and transparent assessments of all residential and commercial properties. We serve every community in the County through ethical stewardship within the property tax system. 
We will achieve our mission through:

#### Data Integrity

High-quality data is essential for fair and equitable assessments. The CCAO is dedicated to excellence and agility in the collection, management, and sharing of data to inform our decisions and mirror the market.

#### Teamwork Culture 

The CCAO is committed to enhancing our employees’ skills through modern tools, techniques and training. This fosters an environment of collaboration and produces the leadership necessary to tackle new opportunities.

#### Distinguished Service

At the CCAO, our aim is to deliver high-caliber services, provide clear and accurate information, and seek feedback to improve our work so we can support the economic vitality of Cook County.

### OUR VALUES
#### FAIRNESS

Deliver accurate and uniform assessments, with timely and informative notices, in compliance with industry standards and guided by best practices.

#### TRANSPARENCY

Build transparency into every part of the office—making services more effective and efficient—and earn the public's trust.

#### ETHICS

Create an office culture of professionalism, inclusion and public accountability, with engaged employees who take pride in the delivery of high-quality, accessible services for all. (Read our Office's ethics code.)